### ISSUE TITLE
Build issue/question

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/zrnt#22]
I'm trying to follow the build instructions with

```
go generate ./...
go build -tags preset_mainnet
```

I get the following error:

```
Justins-MBP:zrnt justin$ go build -tags preset_mainnet
can't load package: package github.com/protolambda/zrnt: unknown import path "github.com/protolambda/zrnt": cannot find module providing package github.com/protolambda/zrnt
```

**Comment by protolambda** [comment]
See #23, I updated the instructions.

What went wrong here:
- No need to re-generate anything if you're not adding new configs
- It's a library, not an executable, so no need to `go build` unless you're doing something more advanced like linking it yourself (which would require more options anyway)
- Build failed because it logically didn't find a build target. You can e.g. do `./...` if you want it to build everything (which would only resolve to build the executable that transforms configs into Go files here). Try `go test -tags preset_minimal ./...` to run spec tests (after downloading them, see readme), or use with ZCLI, Rumor, or your own project to use ZRNT.
