### ISSUE TITLE
Panic when extra data too large

### ISSUE THREAD

**Issue by lightclient** [protolambda/zrnt#37]
Not sure if this should live in `zrnt` or `ztyp`, but I'm finding that if I call `SetLatestExecutionPayloadHeader` with a header whose extra data is greater than 32 bytes it panics with:

```
invalid memory address or nil pointer dereference
```

I feel like it should panic with something more like

```
extra data too big
```

**Comment by protolambda** [comment]
sounds like a problem in ztyp that tries to iterate over the limit due to the unexpected size, will look into it, thanks for reporting.

**Comment by protolambda** [comment]
Not sure where the nil pointer comes from, do you have a way to reproduce this?

- `SetLatestExecutionPayloadHeader` is just a convenience method to updating a sub-tree by converting a flat `ExecutionPayloadHeader` to a typed tree and setting it 
```go
func (state *BeaconStateView) SetLatestExecutionPayloadHeader(h *common.ExecutionPayloadHeader) error {
	return state.Set(_latestExecutionPayloadHeader, h.View())
}
```
- `ExecutionPayloadHeader.View()` is not describing each error location nicely (Go error handling... planning to change tree usage in zrnt dramatically to not error as much), but does panic with the size error:
```go
func TestExecutionPayload_Issue(t *testing.T) {
	header := ExecutionPayloadHeader{
		ExtraData: make(ExtraData, 33),
	}
	v := header.View()
	t.Log(v)
}
```
```
	panic: too many items, limit 32 but got 33
```
The assumption is that the `ExecutionPayloadHeader` is valid, since sizes such as that of the extra-data are already checked during deserialization, or the object is constructed in some trusted way.

**Comment by protolambda** [comment]
Closing some old issues. Fixed this thing with a simple if check: https://github.com/protolambda/zrnt/commit/f5e2b8fb36261cdb22e874a447d53de912877de8
