### ISSUE TITLE
Capella not support HistoricalSummary

### ISSUE THREAD

**Issue by seancheen** [protolambda/zrnt#42]
I used https://github.com/protolambda/eth2-testnet-genesis to generate capella genesis.ssz, and started using prysm and it init error. I found that zrnt does not support HistoricalSummary through debugging

ref: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#historicalsummary

**Comment by protolambda** [comment]
Closing this, can't reproduce probably because it's a very old issue (sorry, was not actively maintaining this while there were no L1 upgrades happening), and support for the `HistoricalSummary` is implemented: https://github.com/protolambda/zrnt/blob/50e164236e0abd5345b4d0b89004c270971dd275/eth2/beacon/capella/history.go#L12
